/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-tint': '#eec14b',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d1c5af',
        'on-background': '#e5e2e1',
        'on-primary': '#3e2e00',
        'on-primary-container': '#473500',
        'on-primary-fixed': '#251a00',
        'on-primary-fixed-variant': '#5a4300',
        primary: '#eec14b',
        'primary-container': '#c59b27',
        'primary-fixed': '#ffdf98',
        'primary-fixed-dim': '#eec14b',
        'inverse-primary': '#775a00',
        secondary: '#ffb77b',
        'secondary-container': '#7a4100',
        'secondary-fixed': '#ffdcc2',
        'secondary-fixed-dim': '#ffb77b',
        'on-secondary': '#4d2700',
        'on-secondary-container': '#ffb270',
        'on-secondary-fixed': '#2e1500',
        'on-secondary-fixed-variant': '#6d3a00',
        tertiary: '#a4d393',
        'tertiary-container': '#80ad70',
        'tertiary-fixed': '#c0f0ad',
        'tertiary-fixed-dim': '#a4d393',
        'on-tertiary': '#113809',
        'on-tertiary-container': '#194010',
        'on-tertiary-fixed': '#022100',
        'on-tertiary-fixed-variant': '#28501e',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#9a907c',
        'outline-variant': '#4e4635',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        // "Dwarf Fortress" stone palette used by the login terminal (stitch/login.html).
        dwarf: {
          abyss: '#0c0b0a',
          bg: '#141312',
          slate: '#1c1a17',
          basalt: '#25221d',
          border: '#3c362d',
          borderLight: '#544c3f',
          parchment: '#d4c5a9',
          parchmentMuted: '#968870',
          gold: '#c59b27',
          goldLight: '#e5a93c',
          goldHover: '#f5be54',
          runeGreen: '#4f7942',
          runeBright: '#629e52',
          magma: '#d34e24',
        },
      },
      boxShadow: {
        'stone-inner':
          'inset 2px 2px 4px rgba(0,0,0,0.8), inset -1px -1px 2px rgba(255,255,255,0.05)',
        'stone-relief':
          '3px 3px 0px #0a0908, -1px -1px 0px rgba(255,255,255,0.07)',
        'gold-glow': '0 0 15px rgba(197, 155, 39, 0.35)',
        'rune-glow': '0 0 12px rgba(79, 121, 66, 0.45)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '3rem',
        'margin-tablet': '2rem',
        margin: '1rem',
        gutter: '1rem',
        'gutter-desktop': '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        sans: ['JetBrains Mono', 'monospace'],
        mono: ['JetBrains Mono', 'monospace'],
        display: ['Space Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '0.04em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '0.03em', fontWeight: '700' }],
        'headline-lg-mobile': ['22px', { lineHeight: '30px', letterSpacing: '0.03em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '0.03em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '0.02em', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '26px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.08em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
