/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-tint': '#eec14b',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d1c5af',
        'on-background': '#e5e2e1',
        'on-primary': '#3e2e00',
        'on-primary-container': '#473500',
        'on-primary-fixed': '#251a00',
        'on-primary-fixed-variant': '#5a4300',
        primary: '#eec14b',
        'primary-container': '#c59b27',
        'primary-fixed': '#ffdf98',
        'primary-fixed-dim': '#eec14b',
        'inverse-primary': '#775a00',
        secondary: '#ffb77b',
        'secondary-container': '#7a4100',
        'secondary-fixed': '#ffdcc2',
        'secondary-fixed-dim': '#ffb77b',
        'on-secondary': '#4d2700',
        'on-secondary-container': '#ffb270',
        'on-secondary-fixed': '#2e1500',
        'on-secondary-fixed-variant': '#6d3a00',
        tertiary: '#a4d393',
        'tertiary-container': '#80ad70',
        'tertiary-fixed': '#c0f0ad',
        'tertiary-fixed-dim': '#a4d393',
        'on-tertiary': '#113809',
        'on-tertiary-container': '#194010',
        'on-tertiary-fixed': '#022100',
        'on-tertiary-fixed-variant': '#28501e',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#9a907c',
        'outline-variant': '#4e4635',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '3rem',
        'margin-tablet': '2rem',
        margin: '1rem',
        gutter: '1rem',
        'gutter-desktop': '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        'headline-xl': ['Space Mono'],
        'headline-xl-mobile': ['Space Mono'],
        'headline-lg': ['Space Mono'],
        'headline-lg-mobile': ['Space Mono'],
        'headline-md': ['Space Mono'],
        'headline-sm': ['Space Mono'],
        'body-lg': ['JetBrains Mono'],
        'body-md': ['JetBrains Mono'],
        'body-sm': ['JetBrains Mono'],
        'label-lg': ['JetBrains Mono'],
        'label-md': ['JetBrains Mono'],
        'label-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-xl-mobile': [
          '28px',
          { lineHeight: '36px', letterSpacing: '0.04em', fontWeight: '700' },
        ],
        'headline-xl': [
          '40px',
          { lineHeight: '48px', letterSpacing: '0.05em', fontWeight: '700' },
        ],
        'headline-lg-mobile': [
          '22px',
          { lineHeight: '30px', letterSpacing: '0.03em', fontWeight: '700' },
        ],
        'headline-lg': [
          '30px',
          { lineHeight: '38px', letterSpacing: '0.03em', fontWeight: '700' },
        ],
        'headline-md': [
          '22px',
          { lineHeight: '30px', letterSpacing: '0.03em', fontWeight: '700' },
        ],
        'headline-sm': [
          '18px',
          { lineHeight: '26px', letterSpacing: '0.02em', fontWeight: '700' },
        ],
        'body-lg': [
          '20px',
          { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '500' },
        ],
        'body-md': [
          '16px',
          { lineHeight: '26px', letterSpacing: '0', fontWeight: '400' },
        ],
        'body-sm': [
          '13px',
          { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' },
        ],
        'label-lg': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.08em', fontWeight: '600' },
        ],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' },
        ],
        'label-sm': [
          '10px',
          { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '500' },
        ],
      },
    },
  },
  plugins: [],
};
